import {
  AlertSeverityLabels,
  AlertSeverityOptions,
  AlertStatusLabels,
  AlertStatusOptions,
  AlertTypeLabels,
  AlertTypeOptions,
  AuthTypeLabels,
  AuthTypeOptions,
  BackupStatusLabels,
  BackupStatusOptions,
  BackupTypeLabels,
  BackupTypeOptions,
  DeviceGroupLabels,
  DeviceGroupOptions,
  DeviceStatusLabels,
  DeviceStatusOptions,
  DeviceTypeLabels,
  DeviceTypeOptions,
  DeviceVendorLabels,
  DeviceVendorOptions,
  DiscoveryStatusLabels,
  DiscoveryStatusOptions,
  InventoryAuditStatusLabels,
  InventoryAuditStatusOptions,
  TaskStatusLabels,
  TaskStatusOptions,
  TemplateStatusLabels,
  TemplateStatusOptions,
  TemplateTypeLabels,
  TemplateTypeOptions,
} from '@/types/enum-labels'

export function useEnumLabels() {
  return {
    labels: {
      DeviceVendorLabels,
      DeviceGroupLabels,
      AuthTypeLabels,
      DeviceStatusLabels,
      DeviceTypeLabels,
      BackupTypeLabels,
      BackupStatusLabels,
      TaskStatusLabels,
      InventoryAuditStatusLabels,
      TemplateTypeLabels,
      TemplateStatusLabels,
      DiscoveryStatusLabels,
      AlertTypeLabels,
      AlertSeverityLabels,
      AlertStatusLabels,
    },
    options: {
      DeviceVendorOptions,
      DeviceGroupOptions,
      AuthTypeOptions,
      DeviceStatusOptions,
      DeviceTypeOptions,
      BackupTypeOptions,
      BackupStatusOptions,
      TaskStatusOptions,
      InventoryAuditStatusOptions,
      TemplateTypeOptions,
      TemplateStatusOptions,
      DiscoveryStatusOptions,
      AlertTypeOptions,
      AlertSeverityOptions,
      AlertStatusOptions,
    },
  }
}

